### PR TITLE
Build OSX + update protobuf + boost

### PR DESCRIPTION
**Pull request by Tobias-Fischer**
Just seeing where it fails for now

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)

### CODE REVIEW

**Comment by Tobias-Fischer** [comment]
@conda-forge-admin, please rerender

**Comment by Tobias-Fischer** [comment]
This now builds okay on OSX, but almost all tests fail due to "Child aborted" exceptions. Any clue why that would be @wolfv @isuruf?

**Comment by wolfv** [comment]
Wow, that's great news! I can try locally on Monday to see if there are exceptions thrown in the test, and what kind of exceptions.

Or we can try to invoke the tests in a different way to see more output. I think there are google test executables in the build folder

**Comment by Tobias-Fischer** [comment]
Still some LUA related stuff: 
```
dyld: Library not loaded: @LUA_PREFIX@/lib/liblua.5.4.dylib
  Referenced from: $SRC_DIR/build/libcartographer.dylib
  Reason: image not found
```

Could that be an issue in the lua build?

**Comment by Tobias-Fischer** [comment]
Ping @wolfv @seanyen @isuruf - any clue what could be wrong regarding the LUA related error?

**Comment by isuruf** [comment]
should be fixed by https://github.com/conda-forge/lua-feedstock/pull/36

**Comment by Tobias-Fischer** [comment]
@conda-forge-admin, please restart ci

**Comment by wolfv** [comment]
ceres-solver 2.0 was released just 8 days ago to conda-forge. We might want to pin 1.x?

**Comment by Tobias-Fischer** [comment]
Unfortunately a couple of the tests failed. I've got no idea of the internals of Ceres;;I'll leave this PR open if someone else would like to take over.

**Comment by wolfv** [comment]
congrats on getting this to build!!
Maybe we should ask upstream? It seems like this is throwing "Illegal Instruction"? Is there any assembly in cartographer or Ceres? ...

**Comment by wolfv** [comment]
https://github.com/cartographer-project/cartographer/issues/1771

**Comment by Tobias-Fischer** [comment]
Fixed the test failure & opened a PR to address the issue upstream.

@seanyen this is ready to be merged

**Comment by Tobias-Fischer** [comment]
@conda-forge-admin, please rerender

**Comment by wolfv** [comment]
Nice!

**Comment by Tobias-Fischer** [comment]
Might as well fix #8 and #9 .. let's see whether that works

**Comment by Tobias-Fischer** [comment]
Looking all green - now it's really ready to be merged @seanyen 
It would be great if you could close #8 & #9 once this PR is merged

**Pull request merged**
