### PR TITLE
Rebuild for protobuf423 and disable Werror

### PR DESCRIPTION
**Pull request by traversaro**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by traversaro** [comment]
@conda-forge-admin, please rerender

**Comment by traversaro** [comment]
Ok, now just 23.2 fails, that it is more expected. The errors are like:
~~~
2023-06-04T15:05:14.8952701Z [252/380] Linking CXX executable cartographer.io.serialization_format_migration_test
2023-06-04T15:05:14.8960482Z FAILED: cartographer.io.serialization_format_migration_test 
2023-06-04T15:05:14.8972990Z : && $BUILD_PREFIX/bin/x86_64-conda-linux-gnu-c++ -fvisibility-inlines-hidden -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem $PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/cartographer-2.0.0 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix -DABSL_LEGACY_THREAD_ANNOTATIONS=1 -O3 -DNDEBUG -Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--disable-new-dtags -Wl,--gc-sections -Wl,--allow-shlib-undefined -Wl,-rpath,$PREFIX/lib -Wl,-rpath-link,$PREFIX/lib -L$PREFIX/lib    -rdynamic CMakeFiles/cartographer.io.serialization_format_migration_test.dir/cartographer/io/serialization_format_migration_test.cc.o -o cartographer.io.serialization_format_migration_test  -Wl,-rpath,$SRC_DIR/build  -lgmock_main  -lgmock  -lgtest  -lpthread  libcartographer_test_library.so  libcartographer.so  $PREFIX/lib/libceres.so.2.1.0  $PREFIX/lib/libglog.so.0.6.0  -llua  -lm  $PREFIX/lib/libboost_iostreams.so.1.78.0  -lglog  $PREFIX/lib/libgflags.so.2.2.2  -lcairo  -lprotobuf  $PREFIX/lib/libabsl_leak_check.so.2301.0.0  $PREFIX/lib/libabsl_cord.so.2301.0.0  $PREFIX/lib/libabsl_cordz_info.so.2301.0.0  $PREFIX/lib/libabsl_cord_internal.so.2301.0.0  $PREFIX/lib/libabsl_cordz_functions.so.2301.0.0  $PREFIX/lib/libabsl_cordz_handle.so.2301.0.0  $PREFIX/lib/libabsl_crc_cord_state.so.2301.0.0  $PREFIX/lib/libabsl_crc32c.so.2301.0.0  $PREFIX/lib/libabsl_crc_internal.so.2301.0.0  $PREFIX/lib/libabsl_crc_cpu_detect.so.2301.0.0  $PREFIX/lib/libabsl_hash.so.2301.0.0  $PREFIX/lib/libabsl_city.so.2301.0.0  $PREFIX/lib/libabsl_bad_variant_access.so.2301.0.0  $PREFIX/lib/libabsl_low_level_hash.so.2301.0.0  $PREFIX/lib/libabsl_raw_hash_set.so.2301.0.0  $PREFIX/lib/libabsl_bad_optional_access.so.2301.0.0  $PREFIX/lib/libabsl_hashtablez_sampler.so.2301.0.0  $PREFIX/lib/libabsl_exponential_biased.so.2301.0.0  $PREFIX/lib/libabsl_str_format_internal.so.2301.0.0  $PREFIX/lib/libabsl_synchronization.so.2301.0.0  $PREFIX/lib/libabsl_stacktrace.so.2301.0.0  $PREFIX/lib/libabsl_graphcycles_internal.so.2301.0.0  $PREFIX/lib/libabsl_symbolize.so.2301.0.0  $PREFIX/lib/libabsl_malloc_internal.so.2301.0.0  $PREFIX/lib/libabsl_debugging_internal.so.2301.0.0  $PREFIX/lib/libabsl_demangle_internal.so.2301.0.0  $PREFIX/lib/libabsl_time.so.2301.0.0  $PREFIX/lib/libabsl_strings.so.2301.0.0  $PREFIX/lib/libabsl_strings_internal.so.2301.0.0  $PREFIX/lib/libabsl_base.so.2301.0.0  $PREFIX/lib/libabsl_spinlock_wait.so.2301.0.0  $PREFIX/lib/libabsl_throw_delegate.so.2301.0.0  $PREFIX/lib/libabsl_raw_logging_internal.so.2301.0.0  $PREFIX/lib/libabsl_log_severity.so.2301.0.0  $PREFIX/lib/libabsl_int128.so.2301.0.0  $PREFIX/lib/libabsl_civil_time.so.2301.0.0  $PREFIX/lib/libabsl_time_zone.so.2301.0.0  -lpthread  -lrt  -lgmock  $PREFIX/lib/libgtest.so.1.13.0  -lpthread && :
2023-06-04T15:05:14.8984846Z $BUILD_PREFIX/bin/../lib/gcc/x86_64-conda-linux-gnu/12.2.0/../../../../x86_64-conda-linux-gnu/bin/ld: CMakeFiles/cartographer.io.serialization_format_migration_test.dir/cartographer/io/serialization_format_migration_test.cc.o: in function `google::protobuf::RepeatedField<float>::GrowNoAnnotate(int, int)':
2023-06-04T15:05:14.9023116Z serialization_format_migration_test.cc:(.text._ZN6google8protobuf13RepeatedFieldIfE14GrowNoAnnotateEii[_ZN6google8protobuf13RepeatedFieldIfE14GrowNoAnnotateEii]+0xa1): undefined reference to `google::protobuf::internal::ThreadSafeArena::thread_cache_'
2023-06-04T15:05:14.9023839Z collect2: error: ld returned 1 exit status
~~~

**Comment by traversaro** [comment]
> Ok, now just 23.2 fails, that it is more expected. The errors are like:
> 
> ```
> 2023-06-04T15:05:14.8952701Z [252/380] Linking CXX executable cartographer.io.serialization_format_migration_test
> 2023-06-04T15:05:14.8960482Z FAILED: cartographer.io.serialization_format_migration_test 
> 2023-06-04T15:05:14.8972990Z : && $BUILD_PREFIX/bin/x86_64-conda-linux-gnu-c++ -fvisibility-inlines-hidden -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem $PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/cartographer-2.0.0 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix -DABSL_LEGACY_THREAD_ANNOTATIONS=1 -O3 -DNDEBUG -Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--disable-new-dtags -Wl,--gc-sections -Wl,--allow-shlib-undefined -Wl,-rpath,$PREFIX/lib -Wl,-rpath-link,$PREFIX/lib -L$PREFIX/lib    -rdynamic CMakeFiles/cartographer.io.serialization_format_migration_test.dir/cartographer/io/serialization_format_migration_test.cc.o -o cartographer.io.serialization_format_migration_test  -Wl,-rpath,$SRC_DIR/build  -lgmock_main  -lgmock  -lgtest  -lpthread  libcartographer_test_library.so  libcartographer.so  $PREFIX/lib/libceres.so.2.1.0  $PREFIX/lib/libglog.so.0.6.0  -llua  -lm  $PREFIX/lib/libboost_iostreams.so.1.78.0  -lglog  $PREFIX/lib/libgflags.so.2.2.2  -lcairo  -lprotobuf  $PREFIX/lib/libabsl_leak_check.so.2301.0.0  $PREFIX/lib/libabsl_cord.so.2301.0.0  $PREFIX/lib/libabsl_cordz_info.so.2301.0.0  $PREFIX/lib/libabsl_cord_internal.so.2301.0.0  $PREFIX/lib/libabsl_cordz_functions.so.2301.0.0  $PREFIX/lib/libabsl_cordz_handle.so.2301.0.0  $PREFIX/lib/libabsl_crc_cord_state.so.2301.0.0  $PREFIX/lib/libabsl_crc32c.so.2301.0.0  $PREFIX/lib/libabsl_crc_internal.so.2301.0.0  $PREFIX/lib/libabsl_crc_cpu_detect.so.2301.0.0  $PREFIX/lib/libabsl_hash.so.2301.0.0  $PREFIX/lib/libabsl_city.so.2301.0.0  $PREFIX/lib/libabsl_bad_variant_access.so.2301.0.0  $PREFIX/lib/libabsl_low_level_hash.so.2301.0.0  $PREFIX/lib/libabsl_raw_hash_set.so.2301.0.0  $PREFIX/lib/libabsl_bad_optional_access.so.2301.0.0  $PREFIX/lib/libabsl_hashtablez_sampler.so.2301.0.0  $PREFIX/lib/libabsl_exponential_biased.so.2301.0.0  $PREFIX/lib/libabsl_str_format_internal.so.2301.0.0  $PREFIX/lib/libabsl_synchronization.so.2301.0.0  $PREFIX/lib/libabsl_stacktrace.so.2301.0.0  $PREFIX/lib/libabsl_graphcycles_internal.so.2301.0.0  $PREFIX/lib/libabsl_symbolize.so.2301.0.0  $PREFIX/lib/libabsl_malloc_internal.so.2301.0.0  $PREFIX/lib/libabsl_debugging_internal.so.2301.0.0  $PREFIX/lib/libabsl_demangle_internal.so.2301.0.0  $PREFIX/lib/libabsl_time.so.2301.0.0  $PREFIX/lib/libabsl_strings.so.2301.0.0  $PREFIX/lib/libabsl_strings_internal.so.2301.0.0  $PREFIX/lib/libabsl_base.so.2301.0.0  $PREFIX/lib/libabsl_spinlock_wait.so.2301.0.0  $PREFIX/lib/libabsl_throw_delegate.so.2301.0.0  $PREFIX/lib/libabsl_raw_logging_internal.so.2301.0.0  $PREFIX/lib/libabsl_log_severity.so.2301.0.0  $PREFIX/lib/libabsl_int128.so.2301.0.0  $PREFIX/lib/libabsl_civil_time.so.2301.0.0  $PREFIX/lib/libabsl_time_zone.so.2301.0.0  -lpthread  -lrt  -lgmock  $PREFIX/lib/libgtest.so.1.13.0  -lpthread && :
> 2023-06-04T15:05:14.8984846Z $BUILD_PREFIX/bin/../lib/gcc/x86_64-conda-linux-gnu/12.2.0/../../../../x86_64-conda-linux-gnu/bin/ld: CMakeFiles/cartographer.io.serialization_format_migration_test.dir/cartographer/io/serialization_format_migration_test.cc.o: in function `google::protobuf::RepeatedField<float>::GrowNoAnnotate(int, int)':
> 2023-06-04T15:05:14.9023116Z serialization_format_migration_test.cc:(.text._ZN6google8protobuf13RepeatedFieldIfE14GrowNoAnnotateEii[_ZN6google8protobuf13RepeatedFieldIfE14GrowNoAnnotateEii]+0xa1): undefined reference to `google::protobuf::internal::ThreadSafeArena::thread_cache_'
> 2023-06-04T15:05:14.9023839Z collect2: error: ld returned 1 exit status
> ```

Ok, the problems seems that `find_package(Protobuf)` was used in place of `find_package(Protobuf CONFIG)`, and the raw library was linked instead of linking to `protobuf::libprotobuf`, so all the usage requirements that since protobuf 23 are important were not propagated, see https://github.com/conda-forge/conda-forge-pinning-feedstock/issues/4075#issuecomment-1569242816 for more details.

**Comment by traversaro** [comment]
@Tobias-Fischer The PR is ready for review.

**Comment by Tobias-Fischer** [comment]
Thanks a lot Silvio, as always amazing work!!

**Pull request merged**
