### PR TITLE
Abseil migration

### PR DESCRIPTION
**Pull request by hmaarrfk**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by hmaarrfk** [comment]
I don't know why the migrator didn't pick this up.

**Comment by Tobias-Fischer** [comment]
We should do the same for the V1 branch

**Comment by hmaarrfk** [comment]
Seems like v1 does not use abseil

**Comment by hmaarrfk** [comment]
https://github.com/conda-forge/cartographer-feedstock/blob/v1/recipe/meta.yaml

**Pull request merged**
